version: "2"
run:
  concurrency: 4
  issues-exit-code: 20
  tests: true
linters:
  default: all
  disable:
    - depguard
    - paralleltest
    - exhaustruct
    - nonamedreturns
    - nlreturn
    - tagalign
  settings:
    cyclop:
      max-complexity: 15
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 17
    lll:
      line-length: 120
      tab-width: 1
    misspell:
      locale: US
    nakedret:
      max-func-lines: 30
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    errcheck:
      check-type-assertions: true
      check-blank: true
    exhaustive:
      default-signifies-exhaustive: true
    wsl:
      allow-trailing-comment: true
    varnamelen:
      ignore-decls:
        - i int
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
    rules:
      - path: _test\.go
        linters:
          - err113
          - funlen
          - lll
          - wsl
          - errorlint
formatters:
  enable:
    - gofmt
    - goimports
    - gci
    - gofumpt
    - golines
  settings:
    golines:
      max-len: 120
  exclusions:
    generated: lax
