name: CI

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.1.5
  
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.22, stable]
    name: test (Go ${{ matrix.go-version }})
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: |
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go test -vet=all -v -run=Test ./...

  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v5
      with:
        files: coverage.txt
        token: ${{secrets.CODECOV_TOKEN}}

  benchmark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - run: go test -bench=. -benchmem -run=Bench ./...
