name: Coverage

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Go 1.x",
            version: "1.x",
          }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.config.version }}

    - name: Coverage
      run: make coverage

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.txt
        token: ${{secrets.CODECOV_TOKEN}}
