name: Coverage

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Go 1.x
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.x
    - run: go test -coverprofile=coverage.txt -covermode=atomic ./...
    - uses: codecov/codecov-action@v5
      with:
        files: coverage.txt
        token: ${{secrets.CODECOV_TOKEN}}
