name: Fuzz

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:
    inputs:
      fuzztime:
        description: "How long to run fuzzing (e.g. 30s, 2m)"
        required: false
        default: "30s"

jobs:

  build:
    name: Go 1.x
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: 1.x

    - name: Quick fuzz
      run: |
        FUZZTIME="${{ inputs.fuzztime || '30s' }}"
        go test ./internal/parser/... -v -fuzz=Fuzz -fuzztime $FUZZTIME
        go test ./internal/interpolator/... -v -fuzz=Fuzz -fuzztime $FUZZTIME
