name: Test

on:
  push:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
  schedule:
    - cron: '0 18 1 * *'

jobs:

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            version: "1.12.x",
          }
          - {
            version: "1.x",
          }

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.config.version }}

    - name: Test
      run: make coverage lint

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: coverage.txt
        token: ${{secrets.CODECOV_TOKEN}}
