name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: Go min supported
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
        cache: false
    - run: go test ./...
    - run: go test -bench=. -benchmem -run=Bench ./...
