name: Test

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  build:
    name: ${{ matrix.config.name }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        config:
          - {
            name: "Go 1.18.x",
            version: "1.18.x",
          }
          - {
            name: "Go 1.x",
            version: "1.x",
          }

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.config.version }}

    - name: Lint
      run: |
        make lint
        git diff --quiet || (echo "\nError. See changed files.\n" && exit 1)

    - name: Test
      run: make test

    - name: Benchmark
      run: make bench
